name: Auto Cancel Redundant Workflow

description: GitHub Actions to automatically cancel redundant workflow.

author: technote-space

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  TARGET_RUN_ID:
    description: Target run id
    default: ${{ github.run_id }}
    required: true
  EXCLUDE_MERGED:
    description: Whether to exclude merge push.
    required: false
    default: 'false'
  MERGE_MESSAGE_PREFIX:
    description: Prefix to detect merge message.
    required: false
    default: 'Merge pull request'
  EXCLUDE_TAG_PUSH:
    description: Whether to exclude tag push.
    required: false
    default: 'true'
  CONSIDER_RE_RUN:
    description: Whether to consider re-run. (Just a simple check of updated_at)
    required: false
    default: 'false'
  INTERVAL_MS:
    description: Interval milliseconds
    required: false

branding:
  icon: 'x-circle'
  color: 'orange'

runs:
  using: node12
  main: lib/main.js
